site_name: pydisplay
repo_url: https://github.com/PyDevices/pydisplay/
copyright: "Copyright 2024, Brad Barnett"
docs_dir: docs
site_dir: site

theme:
#  name: "material"
  name: "readthedocs"
  palette:
    scheme: slate
    primary: indigo
    accent: amber


plugins:
- search
- gen-files:
    scripts:
    - tools/gen_ref_pages.py
- literate-nav:
    nav_file: SUMMARY.md
- section-index
- mkdocstrings:
    handlers:
      python:
        options:
          show_source: false
          show_bases: false
          inherited_members: true
          paths: [src]
          docstring_style: google
          docstring_section_style: table
          separate_signature: true
          show_category_heading: true
          # heading_level: 1
# - mkdocs-pyscript:
#     pyscript_version: "unstable"

nav:
# rest of the navigation...
- About the project:
    - Background: index.md
    - Getting Started: getting-started.md
    - Live Demos: test2.md
- Modules:
  - displaysys:
    - busdisplay:  test-page#src.lib.displaysys.busdisplay
    - fbdisplay:  test-page#src.lib.displaysys.fbdisplay
    - jndisplay:  test-page#src.lib.displaysys.jndisplay
    - pgdisplay:  test-page#src.lib.displaysys.pgdisplay
    - psdisplay:  test-page#src.lib.displaysys.psdisplay
    - sdldisplay:  test-page#src.lib.displaysys.sdldisplay
  - eventsys:  test-page#src.lib.eventsys
  - graphics:  test-page#src.lib.graphics
  - multimer:  test-page#src.lib.multimer
  - palettes:  test-page#src.lib.palettes
- Platforms:
    - Micropython:
      - Embedded:  micropython#embedded
      - Unix:  micropython#unix
      - PyScript:  micropython#pyscript
    - CPython:
      - Desktop:  cpython#desktop
      - Single Board Computer:  cpython#sbc
      - Jupyter Notebook:  cpython#jupyter
      - PyScript:  cpython#pyscript
    - CircuitPython:
      - Embedded:  circuitpython#embedded
      - Blinka:  circuitpython#blinka
      - USB_Video:  circuitpython#usb_video
      - DVI (HDMI):  circuitpython#dvi
      - More - RGBMatrix, IS31FL3741, etc.:  circuitpython#more
- GUIs:
  - LVGL:  lvgl.md
  - MicroPython-Touch:  micropython-touch.md
  - TFT_GUI:  tft_gui.md
  - PyWidgets:  pywidgets.md
# defer to gen-files + literate-nav
- Package Reference: reference/
# rest of the navigation...

markdown_extensions:
  - toc:
      permalink: true
      separator: "_"
