[files]
"../src/jupyter_notebook.ipynb" = "/"
"../src/path.py" = "/"
"../src/configs/board_config.py" = "/configs/"
"../src/configs/color_setup.py" = "/configs/"
"../src/configs/hardware_setup.py" = "/configs/"
"../src/configs/lv_config.py" = "/configs/"
"../src/configs/tft_config.py" = "/configs/"
"../src/configs/__pycache__/board_config.cpython-312.pyc" = "/configs/__pycache__/"

"../src/extras/adafruit_ticks.py" = "/extras/"
"../src/extras/bmp565.py" = "/extras/"
"../src/extras/console.py" = "/extras/"
"../src/extras/ezfont.py" = "/extras/"
"../src/extras/keypins.py" = "/extras/"
"../src/extras/micropython.py" = "/extras/"
"../src/extras/otf_icons.py" = "/extras/"
"../src/extras/pbm.py" = "/extras/"
"../src/extras/png.py" = "/extras/"
"../src/extras/tft_bitmap.py" = "/extras/"
"../src/extras/tft_write.py" = "/extras/"
"../src/extras/wifi.py" = "/extras/"
"../src/extras/pywidgets/__constants__.py" = "/extras/pywidgets/"
"../src/extras/pywidgets/__init__.py" = "/extras/pywidgets/"
"../src/extras/pywidgets/console.py" = "/extras/pywidgets/"
"../src/extras/pywidgets/pct.py" = "/extras/pywidgets/"
"../src/extras/pywidgets/__pycache__/__constants__.cpython-312.pyc" = "/extras/pywidgets/__pycache__/"
"../src/extras/pywidgets/__pycache__/__init__.cpython-312.pyc" = "/extras/pywidgets/__pycache__/"
"../src/extras/pywidgets/__pycache__/pct.cpython-312.pyc" = "/extras/pywidgets/__pycache__/"
"../src/extras/pywidgets/icons/LICENSE" = "/extras/pywidgets/icons/"
"../src/extras/pywidgets/icons/README.md" = "/extras/pywidgets/icons/"
"../src/extras/pywidgets/icons/check_box_36dp.png" = "/extras/pywidgets/icons/"
"../src/extras/pywidgets/icons/check_box_outline_blank_36dp.png" = "/extras/pywidgets/icons/"
"../src/extras/pywidgets/icons/home_filled_36dp.png" = "/extras/pywidgets/icons/"
"../src/extras/pywidgets/icons/keyboard_arrow_down_18dp.png" = "/extras/pywidgets/icons/"
"../src/extras/pywidgets/icons/keyboard_arrow_down_36dp.png" = "/extras/pywidgets/icons/"
"../src/extras/pywidgets/icons/keyboard_arrow_left_18dp.png" = "/extras/pywidgets/icons/"
"../src/extras/pywidgets/icons/keyboard_arrow_left_36dp.png" = "/extras/pywidgets/icons/"
"../src/extras/pywidgets/icons/keyboard_arrow_right_18dp.png" = "/extras/pywidgets/icons/"
"../src/extras/pywidgets/icons/keyboard_arrow_right_36dp.png" = "/extras/pywidgets/icons/"
"../src/extras/pywidgets/icons/keyboard_arrow_up_18dp.png" = "/extras/pywidgets/icons/"
"../src/extras/pywidgets/icons/keyboard_arrow_up_36dp.png" = "/extras/pywidgets/icons/"
"../src/extras/pywidgets/icons/radio_button_checked_36dp.png" = "/extras/pywidgets/icons/"
"../src/extras/pywidgets/icons/radio_button_unchecked_36dp.png" = "/extras/pywidgets/icons/"
"../src/extras/pywidgets/icons/toggle_off_18dp.png" = "/extras/pywidgets/icons/"
"../src/extras/pywidgets/icons/toggle_off_36dp.png" = "/extras/pywidgets/icons/"
"../src/extras/pywidgets/icons/toggle_on_18dp.png" = "/extras/pywidgets/icons/"
"../src/extras/pywidgets/icons/toggle_on_36dp.png" = "/extras/pywidgets/icons/"
"../src/extras/__pycache__/adafruit_ticks.cpython-312.pyc" = "/extras/__pycache__/"
"../src/extras/__pycache__/micropython.cpython-312.pyc" = "/extras/__pycache__/"
"../src/extras/__pycache__/png.cpython-312.pyc" = "/extras/__pycache__/"
"../src/extras/tft_text/__init__.py" = "/extras/tft_text/"
"../src/extras/tft_text/_python.py" = "/extras/tft_text/"
"../src/extras/tft_text/_viper.py" = "/extras/tft_text/"
"../src/extras/tft_text/fonts/__init__.py" = "/extras/tft_text/fonts/"
"../src/extras/tft_text/fonts/compile_upload.sh" = "/extras/tft_text/fonts/"
"../src/extras/tft_text/fonts/vga1_16x16.py" = "/extras/tft_text/fonts/"
"../src/extras/tft_text/fonts/vga1_16x32.py" = "/extras/tft_text/fonts/"
"../src/extras/tft_text/fonts/vga1_8x16.py" = "/extras/tft_text/fonts/"
"../src/extras/tft_text/fonts/vga1_8x8.py" = "/extras/tft_text/fonts/"
"../src/extras/tft_text/fonts/vga1_bold_16x16.py" = "/extras/tft_text/fonts/"
"../src/extras/tft_text/fonts/vga1_bold_16x32.py" = "/extras/tft_text/fonts/"
"../src/extras/tft_text/fonts/vga2_16x16.py" = "/extras/tft_text/fonts/"
"../src/extras/tft_text/fonts/vga2_16x32.py" = "/extras/tft_text/fonts/"
"../src/extras/tft_text/fonts/vga2_8x16.py" = "/extras/tft_text/fonts/"
"../src/extras/tft_text/fonts/vga2_8x8.py" = "/extras/tft_text/fonts/"
"../src/extras/tft_text/fonts/vga2_bold_16x16.py" = "/extras/tft_text/fonts/"
"../src/extras/tft_text/fonts/vga2_bold_16x32.py" = "/extras/tft_text/fonts/"

"../src/lib/buses/spibus/__init__.py" = "/lib/buses/spibus/"

"../src/lib/buses/i80bus/__init__.py" = "/lib/buses/i80bus/"
"../src/lib/buses/i80bus/_gpio_pin.py" = "/lib/buses/i80bus/"
"../src/lib/buses/i80bus/_rp2_wip.py" = "/lib/buses/i80bus/"

"../src/lib/displays/basedisplay/__init__.py" = "/lib/displays/basedisplay/"
"../src/lib/displays/basedisplay/_area.py" = "/lib/displays/basedisplay/"
"../src/lib/displays/basedisplay/_color.py" = "/lib/displays/basedisplay/"
"../src/lib/displays/basedisplay/_numpy.py" = "/lib/displays/basedisplay/"
"../src/lib/displays/basedisplay/_viper.py" = "/lib/displays/basedisplay/"
"../src/lib/displays/basedisplay/__pycache__/__init__.cpython-312.pyc" = "/lib/displays/basedisplay/__pycache__/"
"../src/lib/displays/basedisplay/__pycache__/_area.cpython-312.pyc" = "/lib/displays/basedisplay/__pycache__/"
"../src/lib/displays/basedisplay/__pycache__/_color.cpython-312.pyc" = "/lib/displays/basedisplay/__pycache__/"
"../src/lib/displays/basedisplay/__pycache__/_numpy.cpython-312.pyc" = "/lib/displays/basedisplay/__pycache__/"

"../src/lib/displays/busdisplay/__init__.py" = "/lib/displays/busdisplay/"

"../src/lib/displays/dtdisplay/__init__.py" = "/lib/displays/dtdisplay/"
"../src/lib/displays/dtdisplay/__pycache__/__init__.cpython-312.pyc" = "/lib/displays/dtdisplay/__pycache__/"
"../src/lib/displays/dtdisplay/pgdisplay/__init__.py" = "/lib/displays/dtdisplay/pgdisplay/"
"../src/lib/displays/dtdisplay/pgdisplay/__pycache__/__init__.cpython-312.pyc" = "/lib/displays/dtdisplay/pgdisplay/__pycache__/"
"../src/lib/displays/dtdisplay/sdldisplay/__init__.py" = "/lib/displays/dtdisplay/sdldisplay/"
"../src/lib/displays/dtdisplay/sdldisplay/_sdl2_lib/__init__.py" = "/lib/displays/dtdisplay/sdldisplay/_sdl2_lib/"
"../src/lib/displays/dtdisplay/sdldisplay/_sdl2_lib/_constants.py" = "/lib/displays/dtdisplay/sdldisplay/_sdl2_lib/"
"../src/lib/displays/dtdisplay/sdldisplay/_sdl2_lib/_cpython.py" = "/lib/displays/dtdisplay/sdldisplay/_sdl2_lib/"
"../src/lib/displays/dtdisplay/sdldisplay/_sdl2_lib/_micropython.py" = "/lib/displays/dtdisplay/sdldisplay/_sdl2_lib/"

"../src/lib/displays/fbdisplay/__init__.py" = "/lib/displays/fbdisplay/"

"../src/lib/displays/jndisplay/__init__.py" = "/lib/displays/jndisplay/"

"../src/lib/displays/psdisplay/__init__.py" = "/lib/displays/psdisplay/"

"../src/lib/displays/displaybuf/__init__.py" = "/lib/displays/displaybuf/"
"../src/lib/displays/displaybuf/_viper.py" = "/lib/displays/displaybuf/"

"../src/lib/eventsys/__init__.py" = "/lib/eventsys/"
"../src/lib/eventsys/devices.py" = "/lib/eventsys/"
"../src/lib/eventsys/events.py" = "/lib/eventsys/"
"../src/lib/eventsys/keys.py" = "/lib/eventsys/"
"../src/lib/eventsys/touch_keypad.py" = "/lib/eventsys/"
"../src/lib/eventsys/__pycache__/__init__.cpython-312.pyc" = "/lib/eventsys/__pycache__/"
"../src/lib/eventsys/__pycache__/devices.cpython-312.pyc" = "/lib/eventsys/__pycache__/"
"../src/lib/eventsys/__pycache__/events.cpython-312.pyc" = "/lib/eventsys/__pycache__/"

"../src/lib/framebuf.py" = "/lib/"
"../src/lib/gfx/__init__.py" = "/lib/gfx/"
"../src/lib/gfx/__pycache__/__init__.cpython-312.pyc" = "/lib/gfx/__pycache__/"
"../src/lib/gfx/shapes/__init__.py" = "/lib/gfx/shapes/"
"../src/lib/gfx/shapes/__pycache__/__init__.cpython-312.pyc" = "/lib/gfx/shapes/__pycache__/"
"../src/lib/gfx/framebuf_plus/__init__.py" = "/lib/gfx/framebuf_plus/"
"../src/lib/gfx/framebuf_plus/__pycache__/__init__.cpython-312.pyc" = "/lib/gfx/framebuf_plus/__pycache__/"
"../src/lib/gfx/binfont/__init__.py" = "/lib/gfx/binfont/"
"../src/lib/gfx/binfont/binfont_8x14.bin" = "/lib/gfx/binfont/"
"../src/lib/gfx/binfont/binfont_8x16.bin" = "/lib/gfx/binfont/"
"../src/lib/gfx/binfont/binfont_8x8.bin" = "/lib/gfx/binfont/"
"../src/lib/gfx/binfont/__pycache__/__init__.cpython-312.pyc" = "/lib/gfx/binfont/__pycache__/"

"../src/lib/palettes/__init__.py" = "/lib/palettes/"
"../src/lib/palettes/_cube125.py" = "/lib/palettes/"
"../src/lib/palettes/_cube27.py" = "/lib/palettes/"
"../src/lib/palettes/_cube64.py" = "/lib/palettes/"
"../src/lib/palettes/_cube8.py" = "/lib/palettes/"
"../src/lib/palettes/_material_design.py" = "/lib/palettes/"
"../src/lib/palettes/cube.py" = "/lib/palettes/"
"../src/lib/palettes/material_design.py" = "/lib/palettes/"
"../src/lib/palettes/shades.py" = "/lib/palettes/"
"../src/lib/palettes/wheel.py" = "/lib/palettes/"
"../src/lib/palettes/__pycache__/__init__.cpython-312.pyc" = "/lib/palettes/__pycache__/"
"../src/lib/palettes/__pycache__/_material_design.cpython-312.pyc" = "/lib/palettes/__pycache__/"
"../src/lib/palettes/__pycache__/material_design.cpython-312.pyc" = "/lib/palettes/__pycache__/"

"../src/lib/timer/__init__.py" = "/lib/timer/"
"../src/lib/timer/_librt.py" = "/lib/timer/"
"../src/lib/timer/_sdl2.py" = "/lib/timer/"
"../src/lib/timer/_timerbase.py" = "/lib/timer/"
"../src/lib/timer/__pycache__/__init__.cpython-312.pyc" = "/lib/timer/__pycache__/"
"../src/lib/timer/__pycache__/_sdl2.cpython-312.pyc" = "/lib/timer/__pycache__/"
"../src/lib/timer/__pycache__/_timerbase.cpython-312.pyc" = "/lib/timer/__pycache__/"

