[files]
"../src/add_ons/adafruit_ticks.py" = "/add_ons/"
"../src/add_ons/bmp565.py" = "/add_ons/"
"../src/add_ons/console.py" = "/add_ons/"
"../src/add_ons/ezfont.py" = "/add_ons/"
"../src/add_ons/framebuf.py" = "/add_ons/"
"../src/add_ons/keypins.py" = "/add_ons/"
"../src/add_ons/lv_utils.py" = "/add_ons/"
"../src/add_ons/micropython.py" = "/add_ons/"
"../src/add_ons/pbm.py" = "/add_ons/"
"../src/add_ons/png.py" = "/add_ons/"
"../src/add_ons/romfont.py" = "/add_ons/"
"../src/add_ons/tft_bitmap.py" = "/add_ons/"
"../src/add_ons/tft_write.py" = "/add_ons/"
"../src/add_ons/touch_keypad.py" = "/add_ons/"
"../src/add_ons/wifi.py" = "/add_ons/"
"../src/add_ons/__pycache__/adafruit_ticks.cpython-312.pyc" = "/add_ons/__pycache__/"
"../src/add_ons/__pycache__/framebuf.cpython-312.pyc" = "/add_ons/__pycache__/"
"../src/add_ons/__pycache__/micropython.cpython-312.pyc" = "/add_ons/__pycache__/"
"../src/add_ons/pdwidgets/__init__.py" = "/add_ons/pdwidgets/"
"../src/add_ons/pdwidgets/_constants.py" = "/add_ons/pdwidgets/"
"../src/add_ons/pdwidgets/_themes.py" = "/add_ons/pdwidgets/"
"../src/add_ons/pdwidgets/console.py" = "/add_ons/pdwidgets/"
"../src/add_ons/pdwidgets/pct.py" = "/add_ons/pdwidgets/"
"../src/add_ons/pdwidgets/icons/LICENSE" = "/add_ons/pdwidgets/icons/"
"../src/add_ons/pdwidgets/icons/README.md" = "/add_ons/pdwidgets/icons/"
"../src/add_ons/pdwidgets/icons/check_box_36dp.pbm" = "/add_ons/pdwidgets/icons/"
"../src/add_ons/pdwidgets/icons/check_box_outline_blank_36dp.pbm" = "/add_ons/pdwidgets/icons/"
"../src/add_ons/pdwidgets/icons/home_filled_36dp.pbm" = "/add_ons/pdwidgets/icons/"
"../src/add_ons/pdwidgets/icons/keyboard_arrow_down_18dp.pbm" = "/add_ons/pdwidgets/icons/"
"../src/add_ons/pdwidgets/icons/keyboard_arrow_down_36dp.pbm" = "/add_ons/pdwidgets/icons/"
"../src/add_ons/pdwidgets/icons/keyboard_arrow_left_18dp.pbm" = "/add_ons/pdwidgets/icons/"
"../src/add_ons/pdwidgets/icons/keyboard_arrow_left_36dp.pbm" = "/add_ons/pdwidgets/icons/"
"../src/add_ons/pdwidgets/icons/keyboard_arrow_right_18dp.pbm" = "/add_ons/pdwidgets/icons/"
"../src/add_ons/pdwidgets/icons/keyboard_arrow_right_36dp.pbm" = "/add_ons/pdwidgets/icons/"
"../src/add_ons/pdwidgets/icons/keyboard_arrow_up_18dp.pbm" = "/add_ons/pdwidgets/icons/"
"../src/add_ons/pdwidgets/icons/keyboard_arrow_up_36dp.pbm" = "/add_ons/pdwidgets/icons/"
"../src/add_ons/pdwidgets/icons/radio_button_checked_36dp.pbm" = "/add_ons/pdwidgets/icons/"
"../src/add_ons/pdwidgets/icons/radio_button_unchecked_36dp.pbm" = "/add_ons/pdwidgets/icons/"
"../src/add_ons/pdwidgets/icons/toggle_off_18dp.pbm" = "/add_ons/pdwidgets/icons/"
"../src/add_ons/pdwidgets/icons/toggle_off_36dp.pbm" = "/add_ons/pdwidgets/icons/"
"../src/add_ons/pdwidgets/icons/toggle_on_18dp.pbm" = "/add_ons/pdwidgets/icons/"
"../src/add_ons/pdwidgets/icons/toggle_on_36dp.pbm" = "/add_ons/pdwidgets/icons/"
"../src/add_ons/pdwidgets/__pycache__/__init__.cpython-312.pyc" = "/add_ons/pdwidgets/__pycache__/"
"../src/add_ons/pdwidgets/__pycache__/_constants.cpython-312.pyc" = "/add_ons/pdwidgets/__pycache__/"
"../src/add_ons/pdwidgets/__pycache__/_themes.cpython-312.pyc" = "/add_ons/pdwidgets/__pycache__/"
"../src/add_ons/tft_text/__init__.py" = "/add_ons/tft_text/"
"../src/add_ons/tft_text/_python.py" = "/add_ons/tft_text/"
"../src/add_ons/tft_text/_viper.py" = "/add_ons/tft_text/"
"../src/add_ons/tft_text/fonts/__init__.py" = "/add_ons/tft_text/fonts/"
"../src/add_ons/tft_text/fonts/compile_upload.sh" = "/add_ons/tft_text/fonts/"
"../src/add_ons/tft_text/fonts/vga1_16x16.py" = "/add_ons/tft_text/fonts/"
"../src/add_ons/tft_text/fonts/vga1_16x32.py" = "/add_ons/tft_text/fonts/"
"../src/add_ons/tft_text/fonts/vga1_8x16.py" = "/add_ons/tft_text/fonts/"
"../src/add_ons/tft_text/fonts/vga1_8x8.py" = "/add_ons/tft_text/fonts/"
"../src/add_ons/tft_text/fonts/vga1_bold_16x16.py" = "/add_ons/tft_text/fonts/"
"../src/add_ons/tft_text/fonts/vga1_bold_16x32.py" = "/add_ons/tft_text/fonts/"
"../src/add_ons/tft_text/fonts/vga2_16x16.py" = "/add_ons/tft_text/fonts/"
"../src/add_ons/tft_text/fonts/vga2_16x32.py" = "/add_ons/tft_text/fonts/"
"../src/add_ons/tft_text/fonts/vga2_8x16.py" = "/add_ons/tft_text/fonts/"
"../src/add_ons/tft_text/fonts/vga2_8x8.py" = "/add_ons/tft_text/fonts/"
"../src/add_ons/tft_text/fonts/vga2_bold_16x16.py" = "/add_ons/tft_text/fonts/"
"../src/add_ons/tft_text/fonts/vga2_bold_16x32.py" = "/add_ons/tft_text/fonts/"

"../src/lib/displaybuf/__init__.py" = "/lib/displaybuf/"
"../src/lib/displaybuf/_viper.py" = "/lib/displaybuf/"

"../src/lib/displaysys/__init__.py" = "/lib/displaysys/"
"../src/lib/displaysys/_byteswap.py" = "/lib/displaysys/"
"../src/lib/displaysys/_byteswap_viper.py" = "/lib/displaysys/"
"../src/lib/displaysys/busdisplay.py" = "/lib/displaysys/"
"../src/lib/displaysys/fbdisplay.py" = "/lib/displaysys/"
"../src/lib/displaysys/jndisplay.py" = "/lib/displaysys/"
"../src/lib/displaysys/pgdisplay.py" = "/lib/displaysys/"
"../src/lib/displaysys/psdisplay.py" = "/lib/displaysys/"
"../src/lib/displaysys/sdldisplay/__init__.py" = "/lib/displaysys/sdldisplay/"
"../src/lib/displaysys/sdldisplay/_sdl2_lib/__init__.py" = "/lib/displaysys/sdldisplay/_sdl2_lib/"
"../src/lib/displaysys/sdldisplay/_sdl2_lib/_constants.py" = "/lib/displaysys/sdldisplay/_sdl2_lib/"
"../src/lib/displaysys/sdldisplay/_sdl2_lib/_cpython.py" = "/lib/displaysys/sdldisplay/_sdl2_lib/"
"../src/lib/displaysys/sdldisplay/_sdl2_lib/_micropython.py" = "/lib/displaysys/sdldisplay/_sdl2_lib/"
"../src/lib/displaysys/__pycache__/__init__.cpython-312.pyc" = "/lib/displaysys/__pycache__/"
"../src/lib/displaysys/__pycache__/_byteswap.cpython-312.pyc" = "/lib/displaysys/__pycache__/"
"../src/lib/displaysys/__pycache__/pgdisplay.cpython-312.pyc" = "/lib/displaysys/__pycache__/"

"../src/lib/eventsys/__init__.py" = "/lib/eventsys/"
"../src/lib/eventsys/device.py" = "/lib/eventsys/"
"../src/lib/eventsys/keys.py" = "/lib/eventsys/"
"../src/lib/eventsys/__pycache__/__init__.cpython-312.pyc" = "/lib/eventsys/__pycache__/"
"../src/lib/eventsys/__pycache__/device.cpython-312.pyc" = "/lib/eventsys/__pycache__/"

"../src/lib/graphics/__init__.py" = "/lib/graphics/"
"../src/lib/graphics/_area.py" = "/lib/graphics/"
"../src/lib/graphics/_draw.py" = "/lib/graphics/"
"../src/lib/graphics/_files.py" = "/lib/graphics/"
"../src/lib/graphics/_font.py" = "/lib/graphics/"
"../src/lib/graphics/_framebuf.py" = "/lib/graphics/"
"../src/lib/graphics/_framebuf_plus.py" = "/lib/graphics/"
"../src/lib/graphics/_shapes.py" = "/lib/graphics/"
"../src/lib/graphics/font_8x14.py" = "/lib/graphics/"
"../src/lib/graphics/font_8x16.py" = "/lib/graphics/"
"../src/lib/graphics/font_8x8.py" = "/lib/graphics/"
"../src/lib/graphics/__pycache__/__init__.cpython-312.pyc" = "/lib/graphics/__pycache__/"
"../src/lib/graphics/__pycache__/_area.cpython-312.pyc" = "/lib/graphics/__pycache__/"
"../src/lib/graphics/__pycache__/_draw.cpython-312.pyc" = "/lib/graphics/__pycache__/"
"../src/lib/graphics/__pycache__/_files.cpython-312.pyc" = "/lib/graphics/__pycache__/"
"../src/lib/graphics/__pycache__/_font.cpython-312.pyc" = "/lib/graphics/__pycache__/"
"../src/lib/graphics/__pycache__/_framebuf.cpython-312.pyc" = "/lib/graphics/__pycache__/"
"../src/lib/graphics/__pycache__/_framebuf_plus.cpython-312.pyc" = "/lib/graphics/__pycache__/"
"../src/lib/graphics/__pycache__/_shapes.cpython-312.pyc" = "/lib/graphics/__pycache__/"
"../src/lib/graphics/__pycache__/font_8x14.cpython-312.pyc" = "/lib/graphics/__pycache__/"
"../src/lib/graphics/__pycache__/font_8x16.cpython-312.pyc" = "/lib/graphics/__pycache__/"
"../src/lib/graphics/__pycache__/font_8x8.cpython-312.pyc" = "/lib/graphics/__pycache__/"

"../src/lib/palettes/__init__.py" = "/lib/palettes/"
"../src/lib/palettes/_cube125.py" = "/lib/palettes/"
"../src/lib/palettes/_cube27.py" = "/lib/palettes/"
"../src/lib/palettes/_cube64.py" = "/lib/palettes/"
"../src/lib/palettes/_cube8.py" = "/lib/palettes/"
"../src/lib/palettes/_material_design.py" = "/lib/palettes/"
"../src/lib/palettes/cube.py" = "/lib/palettes/"
"../src/lib/palettes/material_design.py" = "/lib/palettes/"
"../src/lib/palettes/wheel.py" = "/lib/palettes/"
"../src/lib/palettes/__pycache__/__init__.cpython-312.pyc" = "/lib/palettes/__pycache__/"
"../src/lib/palettes/__pycache__/_material_design.cpython-312.pyc" = "/lib/palettes/__pycache__/"
"../src/lib/palettes/__pycache__/material_design.cpython-312.pyc" = "/lib/palettes/__pycache__/"

"../src/lib/timer/__init__.py" = "/lib/timer/"
"../src/lib/timer/_librt.py" = "/lib/timer/"
"../src/lib/timer/_sdl2.py" = "/lib/timer/"
"../src/lib/timer/_timerbase.py" = "/lib/timer/"
"../src/lib/timer/__pycache__/__init__.cpython-312.pyc" = "/lib/timer/__pycache__/"
"../src/lib/timer/__pycache__/_sdl2.cpython-312.pyc" = "/lib/timer/__pycache__/"
"../src/lib/timer/__pycache__/_timerbase.cpython-312.pyc" = "/lib/timer/__pycache__/"

"../src/path.py" = "/"
"../src/jupyter_notebook.ipynb" = "/"
