[files]
"../src/lib/displaybuf/__init__.py" = "/lib/displaybuf/"

"../src/lib/displaysys/__init__.py" = "/lib/displaysys/"
"../src/lib/displaysys/busdisplay.py" = "/lib/displaysys/"
"../src/lib/displaysys/fbdisplay.py" = "/lib/displaysys/"
"../src/lib/displaysys/jndisplay.py" = "/lib/displaysys/"
"../src/lib/displaysys/pgdisplay.py" = "/lib/displaysys/"
"../src/lib/displaysys/psdisplay.py" = "/lib/displaysys/"
"../src/lib/displaysys/sdldisplay/__init__.py" = "/lib/displaysys/sdldisplay/"
"../src/lib/displaysys/sdldisplay/_sdl2_lib/__init__.py" = "/lib/displaysys/sdldisplay/_sdl2_lib/"
"../src/lib/displaysys/sdldisplay/_sdl2_lib/_constants.py" = "/lib/displaysys/sdldisplay/_sdl2_lib/"
"../src/lib/displaysys/sdldisplay/_sdl2_lib/_cpython.py" = "/lib/displaysys/sdldisplay/_sdl2_lib/"
"../src/lib/displaysys/sdldisplay/_sdl2_lib/_micropython.py" = "/lib/displaysys/sdldisplay/_sdl2_lib/"

"../src/lib/eventsys/__init__.py" = "/lib/eventsys/"
"../src/lib/eventsys/device.py" = "/lib/eventsys/"
"../src/lib/eventsys/keys.py" = "/lib/eventsys/"

"../src/lib/graphics/__init__.py" = "/lib/graphics/"
"../src/lib/graphics/_area.py" = "/lib/graphics/"
"../src/lib/graphics/_draw.py" = "/lib/graphics/"
"../src/lib/graphics/_files.py" = "/lib/graphics/"
"../src/lib/graphics/_font.py" = "/lib/graphics/"
"../src/lib/graphics/_framebuf.py" = "/lib/graphics/"
"../src/lib/graphics/_framebuf_plus.py" = "/lib/graphics/"
"../src/lib/graphics/_shapes.py" = "/lib/graphics/"
"../src/lib/graphics/font_8x14.py" = "/lib/graphics/"
"../src/lib/graphics/font_8x16.py" = "/lib/graphics/"
"../src/lib/graphics/font_8x8.py" = "/lib/graphics/"

"../src/lib/palettes/__init__.py" = "/lib/palettes/"
"../src/lib/palettes/_cube125.py" = "/lib/palettes/"
"../src/lib/palettes/_cube27.py" = "/lib/palettes/"
"../src/lib/palettes/_cube64.py" = "/lib/palettes/"
"../src/lib/palettes/_cube8.py" = "/lib/palettes/"
"../src/lib/palettes/_material_design.py" = "/lib/palettes/"
"../src/lib/palettes/cube.py" = "/lib/palettes/"
"../src/lib/palettes/material_design.py" = "/lib/palettes/"
"../src/lib/palettes/wheel.py" = "/lib/palettes/"

"../src/lib/timer/__init__.py" = "/lib/timer/"
"../src/lib/timer/_librt.py" = "/lib/timer/"
"../src/lib/timer/_sdl2.py" = "/lib/timer/"
"../src/lib/timer/_timerbase.py" = "/lib/timer/"

"../src/jupyter_notebook.ipynb" = "/"
