[files]
"../src/jupyter_notebook.ipynb" = "/"
"../src/path.py" = "/"
"../src/configs/board_config.py" = "/configs/"
"../src/configs/color_setup.py" = "/configs/"
"../src/configs/hardware_setup.py" = "/configs/"
"../src/configs/lv_config.py" = "/configs/"
"../src/configs/tft_config.py" = "/configs/"

"../src/extras/bmp565.py" = "/extras/"
"../src/extras/console.py" = "/extras/"
"../src/extras/ezfont.py" = "/extras/"
"../src/extras/keypins.py" = "/extras/"
"../src/extras/pbm.py" = "/extras/"
"../src/extras/png.py" = "/extras/"
"../src/extras/romfont.py" = "/extras/"
"../src/extras/tft_bitmap.py" = "/extras/"
"../src/extras/tft_write.py" = "/extras/"
"../src/extras/wifi.py" = "/extras/"
"../src/extras/tft_text/__init__.py" = "/extras/tft_text/"
"../src/extras/tft_text/_python.py" = "/extras/tft_text/"
"../src/extras/tft_text/_viper.py" = "/extras/tft_text/"
"../src/extras/tft_text/fonts/__init__.py" = "/extras/tft_text/fonts/"
"../src/extras/tft_text/fonts/compile_upload.sh" = "/extras/tft_text/fonts/"
"../src/extras/tft_text/fonts/vga1_16x16.py" = "/extras/tft_text/fonts/"
"../src/extras/tft_text/fonts/vga1_16x32.py" = "/extras/tft_text/fonts/"
"../src/extras/tft_text/fonts/vga1_8x16.py" = "/extras/tft_text/fonts/"
"../src/extras/tft_text/fonts/vga1_8x8.py" = "/extras/tft_text/fonts/"
"../src/extras/tft_text/fonts/vga1_bold_16x16.py" = "/extras/tft_text/fonts/"
"../src/extras/tft_text/fonts/vga1_bold_16x32.py" = "/extras/tft_text/fonts/"
"../src/extras/tft_text/fonts/vga2_16x16.py" = "/extras/tft_text/fonts/"
"../src/extras/tft_text/fonts/vga2_16x32.py" = "/extras/tft_text/fonts/"
"../src/extras/tft_text/fonts/vga2_8x16.py" = "/extras/tft_text/fonts/"
"../src/extras/tft_text/fonts/vga2_8x8.py" = "/extras/tft_text/fonts/"
"../src/extras/tft_text/fonts/vga2_bold_16x16.py" = "/extras/tft_text/fonts/"
"../src/extras/tft_text/fonts/vga2_bold_16x32.py" = "/extras/tft_text/fonts/"

"../src/lib/adafruit_ticks.py" = "/lib/"
"../src/lib/area.py" = "/lib/"
"../src/lib/micropython.py" = "/lib/"
"../src/lib/timer/__init__.py" = "/lib/timer/"
"../src/lib/timer/_librt.py" = "/lib/timer/"
"../src/lib/timer/_sdl2.py" = "/lib/timer/"
"../src/lib/timer/_timerbase.py" = "/lib/timer/"
"../src/lib/buses/spibus.py" = "/lib/buses/"
"../src/lib/buses/i80bus/__init__.py" = "/lib/buses/i80bus/"
"../src/lib/buses/i80bus/_gpio_pin.py" = "/lib/buses/i80bus/"
"../src/lib/buses/i80bus/_rp2_wip.py" = "/lib/buses/i80bus/"
"../src/lib/pygfx/__init__.py" = "/lib/pygfx/"
"../src/lib/pygfx/binfont.py" = "/lib/pygfx/"
"../src/lib/pygfx/binfont_8x14.bin" = "/lib/pygfx/"
"../src/lib/pygfx/binfont_8x16.bin" = "/lib/pygfx/"
"../src/lib/pygfx/binfont_8x8.bin" = "/lib/pygfx/"
"../src/lib/pygfx/framebuf.py" = "/lib/pygfx/"
"../src/lib/pygfx/framebuf_plus.py" = "/lib/pygfx/"
"../src/lib/pygfx/palettes/__init__.py" = "/lib/pygfx/palettes/"
"../src/lib/pygfx/palettes/_cube125.py" = "/lib/pygfx/palettes/"
"../src/lib/pygfx/palettes/_cube27.py" = "/lib/pygfx/palettes/"
"../src/lib/pygfx/palettes/_cube64.py" = "/lib/pygfx/palettes/"
"../src/lib/pygfx/palettes/_cube8.py" = "/lib/pygfx/palettes/"
"../src/lib/pygfx/palettes/_material_design.py" = "/lib/pygfx/palettes/"
"../src/lib/pygfx/palettes/cube.py" = "/lib/pygfx/palettes/"
"../src/lib/pygfx/palettes/material_design.py" = "/lib/pygfx/palettes/"
"../src/lib/pygfx/palettes/shades.py" = "/lib/pygfx/palettes/"
"../src/lib/pygfx/palettes/wheel.py" = "/lib/pygfx/palettes/"
"../src/lib/pygfx/displaybuf/__init__.py" = "/lib/pygfx/displaybuf/"
"../src/lib/pygfx/displaybuf/_viper.py" = "/lib/pygfx/displaybuf/"
"../src/lib/displays/busdisplay.py" = "/lib/displays/"
"../src/lib/displays/dtdisplay.py" = "/lib/displays/"
"../src/lib/displays/fbdisplay.py" = "/lib/displays/"
"../src/lib/displays/jndisplay.py" = "/lib/displays/"
"../src/lib/displays/pgdisplay.py" = "/lib/displays/"
"../src/lib/displays/psdisplay.py" = "/lib/displays/"
"../src/lib/displays/sdldisplay/__init__.py" = "/lib/displays/sdldisplay/"
"../src/lib/displays/sdldisplay/_sdl2_lib/__init__.py" = "/lib/displays/sdldisplay/_sdl2_lib/"
"../src/lib/displays/sdldisplay/_sdl2_lib/_constants.py" = "/lib/displays/sdldisplay/_sdl2_lib/"
"../src/lib/displays/sdldisplay/_sdl2_lib/_cpython.py" = "/lib/displays/sdldisplay/_sdl2_lib/"
"../src/lib/displays/sdldisplay/_sdl2_lib/_micropython.py" = "/lib/displays/sdldisplay/_sdl2_lib/"
"../src/lib/basedisplay/__init__.py" = "/lib/basedisplay/"
"../src/lib/basedisplay/_numpy.py" = "/lib/basedisplay/"
"../src/lib/basedisplay/_viper.py" = "/lib/basedisplay/"
"../src/lib/eventsys/__init__.py" = "/lib/eventsys/"
"../src/lib/eventsys/devices.py" = "/lib/eventsys/"
"../src/lib/eventsys/keys.py" = "/lib/eventsys/"
"../src/lib/eventsys/touch_keypad.py" = "/lib/eventsys/"
"../src/lib/pywidgets/__init__.py" = "/lib/pywidgets/"
"../src/lib/pywidgets/_constants.py" = "/lib/pywidgets/"
"../src/lib/pywidgets/_themes.py" = "/lib/pywidgets/"
"../src/lib/pywidgets/console.py" = "/lib/pywidgets/"
"../src/lib/pywidgets/pct.py" = "/lib/pywidgets/"
"../src/lib/pywidgets/icons/LICENSE" = "/lib/pywidgets/icons/"
"../src/lib/pywidgets/icons/README.md" = "/lib/pywidgets/icons/"
"../src/lib/pywidgets/icons/check_box_36dp.pbm" = "/lib/pywidgets/icons/"
"../src/lib/pywidgets/icons/check_box_36dp.png" = "/lib/pywidgets/icons/"
"../src/lib/pywidgets/icons/check_box_outline_blank_36dp.pbm" = "/lib/pywidgets/icons/"
"../src/lib/pywidgets/icons/check_box_outline_blank_36dp.png" = "/lib/pywidgets/icons/"
"../src/lib/pywidgets/icons/home_filled_36dp.pbm" = "/lib/pywidgets/icons/"
"../src/lib/pywidgets/icons/home_filled_36dp.png" = "/lib/pywidgets/icons/"
"../src/lib/pywidgets/icons/keyboard_arrow_down_18dp.pbm" = "/lib/pywidgets/icons/"
"../src/lib/pywidgets/icons/keyboard_arrow_down_18dp.png" = "/lib/pywidgets/icons/"
"../src/lib/pywidgets/icons/keyboard_arrow_down_36dp.pbm" = "/lib/pywidgets/icons/"
"../src/lib/pywidgets/icons/keyboard_arrow_down_36dp.png" = "/lib/pywidgets/icons/"
"../src/lib/pywidgets/icons/keyboard_arrow_left_18dp.pbm" = "/lib/pywidgets/icons/"
"../src/lib/pywidgets/icons/keyboard_arrow_left_18dp.png" = "/lib/pywidgets/icons/"
"../src/lib/pywidgets/icons/keyboard_arrow_left_36dp.pbm" = "/lib/pywidgets/icons/"
"../src/lib/pywidgets/icons/keyboard_arrow_left_36dp.png" = "/lib/pywidgets/icons/"
"../src/lib/pywidgets/icons/keyboard_arrow_right_18dp.pbm" = "/lib/pywidgets/icons/"
"../src/lib/pywidgets/icons/keyboard_arrow_right_18dp.png" = "/lib/pywidgets/icons/"
"../src/lib/pywidgets/icons/keyboard_arrow_right_36dp.pbm" = "/lib/pywidgets/icons/"
"../src/lib/pywidgets/icons/keyboard_arrow_right_36dp.png" = "/lib/pywidgets/icons/"
"../src/lib/pywidgets/icons/keyboard_arrow_up_18dp.pbm" = "/lib/pywidgets/icons/"
"../src/lib/pywidgets/icons/keyboard_arrow_up_18dp.png" = "/lib/pywidgets/icons/"
"../src/lib/pywidgets/icons/keyboard_arrow_up_36dp.pbm" = "/lib/pywidgets/icons/"
"../src/lib/pywidgets/icons/keyboard_arrow_up_36dp.png" = "/lib/pywidgets/icons/"
"../src/lib/pywidgets/icons/radio_button_checked_36dp.pbm" = "/lib/pywidgets/icons/"
"../src/lib/pywidgets/icons/radio_button_checked_36dp.png" = "/lib/pywidgets/icons/"
"../src/lib/pywidgets/icons/radio_button_unchecked_36dp.pbm" = "/lib/pywidgets/icons/"
"../src/lib/pywidgets/icons/radio_button_unchecked_36dp.png" = "/lib/pywidgets/icons/"
"../src/lib/pywidgets/icons/toggle_off_18dp.pbm" = "/lib/pywidgets/icons/"
"../src/lib/pywidgets/icons/toggle_off_18dp.png" = "/lib/pywidgets/icons/"
"../src/lib/pywidgets/icons/toggle_off_36dp.pbm" = "/lib/pywidgets/icons/"
"../src/lib/pywidgets/icons/toggle_off_36dp.png" = "/lib/pywidgets/icons/"
"../src/lib/pywidgets/icons/toggle_on_18dp.pbm" = "/lib/pywidgets/icons/"
"../src/lib/pywidgets/icons/toggle_on_18dp.png" = "/lib/pywidgets/icons/"
"../src/lib/pywidgets/icons/toggle_on_36dp.pbm" = "/lib/pywidgets/icons/"
"../src/lib/pywidgets/icons/toggle_on_36dp.png" = "/lib/pywidgets/icons/"

