[files]
"../src/add_ons/README.md" = "/add_ons/"
"../src/add_ons/adafruit_ticks.py" = "/add_ons/"
"../src/add_ons/bmp565.py" = "/add_ons/"
"../src/add_ons/byteswap.py" = "/add_ons/"
"../src/add_ons/color_setup.py" = "/add_ons/"
"../src/add_ons/console.py" = "/add_ons/"
"../src/add_ons/display_driver.py" = "/add_ons/"
"../src/add_ons/ezfont.py" = "/add_ons/"
"../src/add_ons/framebuf.py" = "/add_ons/"
"../src/add_ons/hardware_setup.py" = "/add_ons/"
"../src/add_ons/keypins.py" = "/add_ons/"
"../src/add_ons/lv_timer.py" = "/add_ons/"
"../src/add_ons/lv_utils.py" = "/add_ons/"
"../src/add_ons/micropython.py" = "/add_ons/"
"../src/add_ons/pbm.py" = "/add_ons/"
"../src/add_ons/png.py" = "/add_ons/"
"../src/add_ons/romfont.py" = "/add_ons/"
"../src/add_ons/tft_bitmap.py" = "/add_ons/"
"../src/add_ons/tft_config.py" = "/add_ons/"
"../src/add_ons/tft_text.py" = "/add_ons/"
"../src/add_ons/tft_write.py" = "/add_ons/"
"../src/add_ons/touch_keypad.py" = "/add_ons/"
"../src/add_ons/viper_tools.py" = "/add_ons/"
"../src/add_ons/wifi.py" = "/add_ons/"
"../src/add_ons/fonts/__init__.py" = "/add_ons/fonts/"
"../src/add_ons/fonts/compile_upload.sh" = "/add_ons/fonts/"
"../src/add_ons/fonts/vga1_16x16.py" = "/add_ons/fonts/"
"../src/add_ons/fonts/vga1_16x32.py" = "/add_ons/fonts/"
"../src/add_ons/fonts/vga1_8x16.py" = "/add_ons/fonts/"
"../src/add_ons/fonts/vga1_8x8.py" = "/add_ons/fonts/"
"../src/add_ons/fonts/vga1_bold_16x16.py" = "/add_ons/fonts/"
"../src/add_ons/fonts/vga1_bold_16x32.py" = "/add_ons/fonts/"
"../src/add_ons/fonts/vga2_16x16.py" = "/add_ons/fonts/"
"../src/add_ons/fonts/vga2_16x32.py" = "/add_ons/fonts/"
"../src/add_ons/fonts/vga2_8x16.py" = "/add_ons/fonts/"
"../src/add_ons/fonts/vga2_8x8.py" = "/add_ons/fonts/"
"../src/add_ons/fonts/vga2_bold_16x16.py" = "/add_ons/fonts/"
"../src/add_ons/fonts/vga2_bold_16x32.py" = "/add_ons/fonts/"
"../src/add_ons/pdwidgets/__init__.py" = "/add_ons/pdwidgets/"
"../src/add_ons/pdwidgets/_constants.py" = "/add_ons/pdwidgets/"
"../src/add_ons/pdwidgets/_themes.py" = "/add_ons/pdwidgets/"
"../src/add_ons/pdwidgets/console.py" = "/add_ons/pdwidgets/"
"../src/add_ons/pdwidgets/pct.py" = "/add_ons/pdwidgets/"
"../src/add_ons/pdwidgets/icons/LICENSE" = "/add_ons/pdwidgets/icons/"
"../src/add_ons/pdwidgets/icons/README.md" = "/add_ons/pdwidgets/icons/"
"../src/add_ons/pdwidgets/icons/check_box_36dp.pbm" = "/add_ons/pdwidgets/icons/"
"../src/add_ons/pdwidgets/icons/check_box_outline_blank_36dp.pbm" = "/add_ons/pdwidgets/icons/"
"../src/add_ons/pdwidgets/icons/home_filled_36dp.pbm" = "/add_ons/pdwidgets/icons/"
"../src/add_ons/pdwidgets/icons/keyboard_arrow_down_18dp.pbm" = "/add_ons/pdwidgets/icons/"
"../src/add_ons/pdwidgets/icons/keyboard_arrow_down_36dp.pbm" = "/add_ons/pdwidgets/icons/"
"../src/add_ons/pdwidgets/icons/keyboard_arrow_left_18dp.pbm" = "/add_ons/pdwidgets/icons/"
"../src/add_ons/pdwidgets/icons/keyboard_arrow_left_36dp.pbm" = "/add_ons/pdwidgets/icons/"
"../src/add_ons/pdwidgets/icons/keyboard_arrow_right_18dp.pbm" = "/add_ons/pdwidgets/icons/"
"../src/add_ons/pdwidgets/icons/keyboard_arrow_right_36dp.pbm" = "/add_ons/pdwidgets/icons/"
"../src/add_ons/pdwidgets/icons/keyboard_arrow_up_18dp.pbm" = "/add_ons/pdwidgets/icons/"
"../src/add_ons/pdwidgets/icons/keyboard_arrow_up_36dp.pbm" = "/add_ons/pdwidgets/icons/"
"../src/add_ons/pdwidgets/icons/radio_button_checked_36dp.pbm" = "/add_ons/pdwidgets/icons/"
"../src/add_ons/pdwidgets/icons/radio_button_unchecked_36dp.pbm" = "/add_ons/pdwidgets/icons/"
"../src/add_ons/pdwidgets/icons/toggle_off_18dp.pbm" = "/add_ons/pdwidgets/icons/"
"../src/add_ons/pdwidgets/icons/toggle_off_36dp.pbm" = "/add_ons/pdwidgets/icons/"
"../src/add_ons/pdwidgets/icons/toggle_on_18dp.pbm" = "/add_ons/pdwidgets/icons/"
"../src/add_ons/pdwidgets/icons/toggle_on_36dp.pbm" = "/add_ons/pdwidgets/icons/"

"../src/lib/displaybuf/__init__.py" = "/lib/displaybuf/"

"../src/lib/board_config.py" = "/lib/"
"../src/lib/path.py" = "/lib/"
"../src/lib/displaysys/__init__.py" = "/lib/displaysys/"
"../src/lib/displaysys/busdisplay.py" = "/lib/displaysys/"
"../src/lib/displaysys/fbdisplay.py" = "/lib/displaysys/"
"../src/lib/displaysys/jndisplay.py" = "/lib/displaysys/"
"../src/lib/displaysys/pgdisplay.py" = "/lib/displaysys/"
"../src/lib/displaysys/psdisplay.py" = "/lib/displaysys/"
"../src/lib/displaysys/sdldisplay/__init__.py" = "/lib/displaysys/sdldisplay/"
"../src/lib/displaysys/sdldisplay/_sdl2_lib/__init__.py" = "/lib/displaysys/sdldisplay/_sdl2_lib/"
"../src/lib/displaysys/sdldisplay/_sdl2_lib/_constants.py" = "/lib/displaysys/sdldisplay/_sdl2_lib/"
"../src/lib/displaysys/sdldisplay/_sdl2_lib/_cpython.py" = "/lib/displaysys/sdldisplay/_sdl2_lib/"
"../src/lib/displaysys/sdldisplay/_sdl2_lib/_micropython.py" = "/lib/displaysys/sdldisplay/_sdl2_lib/"

"../src/lib/eventsys/__init__.py" = "/lib/eventsys/"
"../src/lib/eventsys/devices.py" = "/lib/eventsys/"
"../src/lib/eventsys/keys.py" = "/lib/eventsys/"

"../src/lib/graphics/__init__.py" = "/lib/graphics/"
"../src/lib/graphics/_area.py" = "/lib/graphics/"
"../src/lib/graphics/_draw.py" = "/lib/graphics/"
"../src/lib/graphics/_files.py" = "/lib/graphics/"
"../src/lib/graphics/_font.py" = "/lib/graphics/"
"../src/lib/graphics/_framebuf.py" = "/lib/graphics/"
"../src/lib/graphics/_framebuf_plus.py" = "/lib/graphics/"
"../src/lib/graphics/_shapes.py" = "/lib/graphics/"
"../src/lib/graphics/font_8x14.py" = "/lib/graphics/"
"../src/lib/graphics/font_8x16.py" = "/lib/graphics/"
"../src/lib/graphics/font_8x8.py" = "/lib/graphics/"

"../src/lib/multimer/__init__.py" = "/lib/multimer/"
"../src/lib/multimer/_librt.py" = "/lib/multimer/"
"../src/lib/multimer/_sdl2.py" = "/lib/multimer/"
"../src/lib/multimer/_timerbase.py" = "/lib/multimer/"

"../src/lib/palettes/__init__.py" = "/lib/palettes/"
"../src/lib/palettes/_cube125.py" = "/lib/palettes/"
"../src/lib/palettes/_cube27.py" = "/lib/palettes/"
"../src/lib/palettes/_cube64.py" = "/lib/palettes/"
"../src/lib/palettes/_cube8.py" = "/lib/palettes/"
"../src/lib/palettes/_material_design.py" = "/lib/palettes/"
"../src/lib/palettes/cube.py" = "/lib/palettes/"
"../src/lib/palettes/material_design.py" = "/lib/palettes/"
"../src/lib/palettes/wheel.py" = "/lib/palettes/"

"../src/jupyter_notebook.ipynb" = "/"
"../src/src/lib/board_config.py" = "/src/lib/"
"../src/src/lib/path.py" = "/src/lib/"
