[files]
"../src/configs/board_config.py" = "/configs/"
"../src/configs/color_setup.py" = "/configs/"
"../src/configs/hardware_setup.py" = "/configs/"
"../src/configs/lv_config.py" = "/configs/"
"../src/configs/tft_config.py" = "/configs/"

"../src/displays/busdisplay.py" = "/displays/"
"../src/displays/dtdisplay.py" = "/displays/"
"../src/displays/fbdisplay.py" = "/displays/"
"../src/displays/jndisplay.py" = "/displays/"
"../src/displays/pgdisplay.py" = "/displays/"
"../src/displays/psdisplay.py" = "/displays/"
"../src/displays/sdldisplay/__init__.py" = "/displays/sdldisplay/"
"../src/displays/sdldisplay/_sdl2_lib/__init__.py" = "/displays/sdldisplay/_sdl2_lib/"
"../src/displays/sdldisplay/_sdl2_lib/_constants.py" = "/displays/sdldisplay/_sdl2_lib/"
"../src/displays/sdldisplay/_sdl2_lib/_cpython.py" = "/displays/sdldisplay/_sdl2_lib/"
"../src/displays/sdldisplay/_sdl2_lib/_micropython.py" = "/displays/sdldisplay/_sdl2_lib/"

"../src/extras/bmp565.py" = "/extras/"
"../src/extras/console.py" = "/extras/"
"../src/extras/ezfont.py" = "/extras/"
"../src/extras/keypins.py" = "/extras/"
"../src/extras/pbm.py" = "/extras/"
"../src/extras/png.py" = "/extras/"
"../src/extras/romfont.py" = "/extras/"
"../src/extras/tft_bitmap.py" = "/extras/"
"../src/extras/tft_write.py" = "/extras/"
"../src/extras/wifi.py" = "/extras/"
"../src/extras/tft_text/__init__.py" = "/extras/tft_text/"
"../src/extras/tft_text/_python.py" = "/extras/tft_text/"
"../src/extras/tft_text/_viper.py" = "/extras/tft_text/"
"../src/extras/tft_text/fonts/__init__.py" = "/extras/tft_text/fonts/"
"../src/extras/tft_text/fonts/compile_upload.sh" = "/extras/tft_text/fonts/"
"../src/extras/tft_text/fonts/vga1_16x16.py" = "/extras/tft_text/fonts/"
"../src/extras/tft_text/fonts/vga1_16x32.py" = "/extras/tft_text/fonts/"
"../src/extras/tft_text/fonts/vga1_8x16.py" = "/extras/tft_text/fonts/"
"../src/extras/tft_text/fonts/vga1_8x8.py" = "/extras/tft_text/fonts/"
"../src/extras/tft_text/fonts/vga1_bold_16x16.py" = "/extras/tft_text/fonts/"
"../src/extras/tft_text/fonts/vga1_bold_16x32.py" = "/extras/tft_text/fonts/"
"../src/extras/tft_text/fonts/vga2_16x16.py" = "/extras/tft_text/fonts/"
"../src/extras/tft_text/fonts/vga2_16x32.py" = "/extras/tft_text/fonts/"
"../src/extras/tft_text/fonts/vga2_8x16.py" = "/extras/tft_text/fonts/"
"../src/extras/tft_text/fonts/vga2_8x8.py" = "/extras/tft_text/fonts/"
"../src/extras/tft_text/fonts/vga2_bold_16x16.py" = "/extras/tft_text/fonts/"
"../src/extras/tft_text/fonts/vga2_bold_16x32.py" = "/extras/tft_text/fonts/"

"../src/lib/adafruit_ticks.py" = "/lib/"
"../src/lib/micropython.py" = "/lib/"
"../src/lib/path.py" = "/lib/"
"../src/lib/pydevices/__init__.py" = "/lib/pydevices/"
"../src/lib/pydevices/_numpy.py" = "/lib/pydevices/"
"../src/lib/pydevices/_viper.py" = "/lib/pydevices/"
"../src/lib/pydevices/devices.py" = "/lib/pydevices/"
"../src/lib/pydevices/keys.py" = "/lib/pydevices/"
"../src/lib/pydevices/touch_keypad.py" = "/lib/pydevices/"
"../src/lib/pydevices/timer/__init__.py" = "/lib/pydevices/timer/"
"../src/lib/pydevices/timer/_librt.py" = "/lib/pydevices/timer/"
"../src/lib/pydevices/timer/_sdl2.py" = "/lib/pydevices/timer/"
"../src/lib/pydevices/timer/_timerbase.py" = "/lib/pydevices/timer/"
"../src/lib/pydevices/displaybuf/__init__.py" = "/lib/pydevices/displaybuf/"
"../src/lib/pydevices/displaybuf/_viper.py" = "/lib/pydevices/displaybuf/"

"../src/lib/pygraphics/__init__.py" = "/lib/pygraphics/"
"../src/lib/pygraphics/binfont.py" = "/lib/pygraphics/"
"../src/lib/pygraphics/binfont_8x14.bin" = "/lib/pygraphics/"
"../src/lib/pygraphics/binfont_8x16.bin" = "/lib/pygraphics/"
"../src/lib/pygraphics/binfont_8x8.bin" = "/lib/pygraphics/"
"../src/lib/pygraphics/framebuf.py" = "/lib/pygraphics/"
"../src/lib/pygraphics/framebuf_plus.py" = "/lib/pygraphics/"

"../src/lib/pypalettes/__init__.py" = "/lib/pypalettes/"
"../src/lib/pypalettes/_cube125.py" = "/lib/pypalettes/"
"../src/lib/pypalettes/_cube27.py" = "/lib/pypalettes/"
"../src/lib/pypalettes/_cube64.py" = "/lib/pypalettes/"
"../src/lib/pypalettes/_cube8.py" = "/lib/pypalettes/"
"../src/lib/pypalettes/_material_design.py" = "/lib/pypalettes/"
"../src/lib/pypalettes/cube.py" = "/lib/pypalettes/"
"../src/lib/pypalettes/material_design.py" = "/lib/pypalettes/"
"../src/lib/pypalettes/wheel.py" = "/lib/pypalettes/"

"../src/lib/pywidgets/__init__.py" = "/lib/pywidgets/"
"../src/lib/pywidgets/_constants.py" = "/lib/pywidgets/"
"../src/lib/pywidgets/_themes.py" = "/lib/pywidgets/"
"../src/lib/pywidgets/console.py" = "/lib/pywidgets/"
"../src/lib/pywidgets/pct.py" = "/lib/pywidgets/"
"../src/lib/pywidgets/icons/LICENSE" = "/lib/pywidgets/icons/"
"../src/lib/pywidgets/icons/README.md" = "/lib/pywidgets/icons/"
"../src/lib/pywidgets/icons/check_box_36dp.pbm" = "/lib/pywidgets/icons/"
"../src/lib/pywidgets/icons/check_box_outline_blank_36dp.pbm" = "/lib/pywidgets/icons/"
"../src/lib/pywidgets/icons/home_filled_36dp.pbm" = "/lib/pywidgets/icons/"
"../src/lib/pywidgets/icons/keyboard_arrow_down_18dp.pbm" = "/lib/pywidgets/icons/"
"../src/lib/pywidgets/icons/keyboard_arrow_down_36dp.pbm" = "/lib/pywidgets/icons/"
"../src/lib/pywidgets/icons/keyboard_arrow_left_18dp.pbm" = "/lib/pywidgets/icons/"
"../src/lib/pywidgets/icons/keyboard_arrow_left_36dp.pbm" = "/lib/pywidgets/icons/"
"../src/lib/pywidgets/icons/keyboard_arrow_right_18dp.pbm" = "/lib/pywidgets/icons/"
"../src/lib/pywidgets/icons/keyboard_arrow_right_36dp.pbm" = "/lib/pywidgets/icons/"
"../src/lib/pywidgets/icons/keyboard_arrow_up_18dp.pbm" = "/lib/pywidgets/icons/"
"../src/lib/pywidgets/icons/keyboard_arrow_up_36dp.pbm" = "/lib/pywidgets/icons/"
"../src/lib/pywidgets/icons/radio_button_checked_36dp.pbm" = "/lib/pywidgets/icons/"
"../src/lib/pywidgets/icons/radio_button_unchecked_36dp.pbm" = "/lib/pywidgets/icons/"
"../src/lib/pywidgets/icons/toggle_off_18dp.pbm" = "/lib/pywidgets/icons/"
"../src/lib/pywidgets/icons/toggle_off_36dp.pbm" = "/lib/pywidgets/icons/"
"../src/lib/pywidgets/icons/toggle_on_18dp.pbm" = "/lib/pywidgets/icons/"
"../src/lib/pywidgets/icons/toggle_on_36dp.pbm" = "/lib/pywidgets/icons/"

